language: node_js
node_js:
  - "0.12"

before_script: npm run data

script: npm run test-lcov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls

notifications:
  email: false
